-- Migration script to create the 'orders' table

-- Create the orders table
CREATE TABLE public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Auto-incrementing primary key
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL, -- Timestamp when the order was created
  user_name TEXT,                                -- Customer's name
  user_email TEXT,                               -- Customer's email
  user_phone TEXT,                               -- Customer's phone (optional)
  user_address TEXT,                             -- Customer's full address
  order_items JSONB,                             -- Details of items ordered (as JSON)
  total_amount NUMERIC,                          -- Total cost of the order
  payment_confirmed BOOLEAN DEFAULT false        -- Flag for payment status
);

-- Optional: Add comments describing the table and columns
COMMENT ON TABLE public.orders IS 'Stores customer order information.';
COMMENT ON COLUMN public.orders.order_items IS 'JSON array of objects, each with id, name, quantity, price, size';
COMMENT ON COLUMN public.orders.payment_confirmed IS 'Set to true once payment is verified';

-- IMPORTANT: Disable Row Level Security (RLS) for initial testing ONLY
-- You MUST enable RLS and define policies before going live for security.
ALTER TABLE public.orders DISABLE ROW LEVEL SECURITY;
